import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import SidebarLayout from "@/components/modules/sidebar";

export const metadata: Metadata = {
  title: "Yones Maheri - Admin Panel",
  description: "Generated by create next app",
};

const vazir = Vazirmatn({
  variable: "--font-vazir",
  subsets: ["arabic"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <SidebarLayout>{children}</SidebarLayout>;
}
