import type { Metadata } from "next";
import "./globals.css";
import { Vazirmatn } from "next/font/google";
import Wrapper from "@/components/modules/wrapper";

export const metadata: Metadata = {
  title: "Yones Maheri - Admin Panel",
  description: "Generated by create next app",
};

const geistSans = Vazirmatn({
  variable: "--font-vazir",
  subsets: ["arabic"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className}`}>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
